/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BookingId = IDL.Nat;
export const Booking = IDL.Record({
  'id' : BookingId,
  'serviceType' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'preferredTimeSlot' : IDL.Text,
  'preferredDate' : IDL.Int,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'submitBooking' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Text, IDL.Int],
      [],
      [],
    ),
  'submitMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BookingId = IDL.Nat;
  const Booking = IDL.Record({
    'id' : BookingId,
    'serviceType' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'preferredTimeSlot' : IDL.Text,
    'preferredDate' : IDL.Int,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'submitBooking' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int, IDL.Text, IDL.Int],
        [],
        [],
      ),
    'submitMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Int],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };